[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "source /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "source /opt/venv/bin/activate && python bot.py"
